<?php
// Do not edit this file. Generated by admin script.
// VehicleManager Configuration file
// General Informations 
$vehiclemanager_configuration['release']['version']='3.7 Free';
$vehiclemanager_configuration['release']['date']='01 October 2015';
// edit vehicle 
$vehiclemanager_configuration['editvehicle']['default']['lang']='';
// price settings
$vehiclemanager_configuration['price']['show']='1';
$vehiclemanager_configuration['price']['registrationlevel']='-2';
// auto increment for vehicleid, if 1 - can't add random vehicleid 
$vehiclemanager_configuration['vehicleid']['auto-increment']['boolean']='0';
// review settings
$vehiclemanager_configuration['reviews']['show']='1';
$vehiclemanager_configuration['reviews']['registrationlevel']='-2';
// show contacts
$vehiclemanager_configuration['Contacts']['show']='1';
$vehiclemanager_configuration ['contacts']['registrationlevel']='-2';
// show cb_myvehicle
$vehiclemanager_configuration['cb_myvehicle']['show']='0';
$vehiclemanager_configuration['cb_myvehicle']['registrationlevel']='';
// show cb_edit
$vehiclemanager_configuration['cb_edit']['show']='0';
$vehiclemanager_configuration['cb_edit']['registrationlevel']='';
// show cb_rent
$vehiclemanager_configuration['cb_rent']['show']='0';
$vehiclemanager_configuration['cb_rent']['registrationlevel']='';
// show cb_buy
$vehiclemanager_configuration['cb_buy']['show']='0';
$vehiclemanager_configuration['cb_buy']['registrationlevel']='';
// show cb_history
$vehiclemanager_configuration['cb_history']['show']='0';
$vehiclemanager_configuration['cb_history']['registrationlevel']='';
// show Location
$vehiclemanager_configuration['Location_vehicle']['show']='1';
$vehiclemanager_configuration ['Location_vehicle']['registrationlevel']='-2';
$vehiclemanager_configuration['Reviews_vehicle']['show']='1';
$vehiclemanager_configuration ['Reviews_vehicle']['registrationlevel'] ='-2';
// rent settings
$vehiclemanager_configuration['rentstatus']['show']='1';
$vehiclemanager_configuration['rentrequest']['registrationlevel']='-2';
// buy settings
$vehiclemanager_configuration['buystatus']['show']='1';
$vehiclemanager_configuration['buyrequest']['registrationlevel']='-2,6';
//user manager
$vehiclemanager_configuration['user_manager_vm']['-2']['count_car']='5';
$vehiclemanager_configuration['user_manager_vm']['-2']['count_foto']='5';
$vehiclemanager_configuration['user_manager_vm']['29']['count_car']='5';
$vehiclemanager_configuration['user_manager_vm']['29']['count_foto']='';
$vehiclemanager_configuration['user_manager_vm']['18']['count_car']='5';
$vehiclemanager_configuration['user_manager_vm']['18']['count_foto']='';
$vehiclemanager_configuration['user_manager_vm']['19']['count_car']='5';
$vehiclemanager_configuration['user_manager_vm']['19']['count_foto']='';
$vehiclemanager_configuration['user_manager_vm']['20']['count_car']='5';
$vehiclemanager_configuration['user_manager_vm']['20']['count_foto']='';
$vehiclemanager_configuration['user_manager_vm']['21']['count_car']='5';
$vehiclemanager_configuration['user_manager_vm']['21']['count_foto']='';
$vehiclemanager_configuration['user_manager_vm']['32']['count_car']='5';
$vehiclemanager_configuration['user_manager_vm']['32']['count_foto']='';
$vehiclemanager_configuration['user_manager_vm']['30']['count_car']='5';
$vehiclemanager_configuration['user_manager_vm']['30']['count_foto']='';
$vehiclemanager_configuration['user_manager_vm']['23']['count_car']='5';
$vehiclemanager_configuration['user_manager_vm']['23']['count_foto']='';
$vehiclemanager_configuration['user_manager_vm']['24']['count_car']='5';
$vehiclemanager_configuration['user_manager_vm']['24']['count_foto']='';
$vehiclemanager_configuration['user_manager_vm']['25']['count_car']='5';
$vehiclemanager_configuration['user_manager_vm']['25']['count_foto']='';
$vehiclemanager_configuration['user_manager_vm']['']['count_car']='0';
$vehiclemanager_configuration['user_manager_vm']['']['count_foto']='';
$vehiclemanager_configuration['user_manager_vm']['1']['count_car']='5';
$vehiclemanager_configuration['user_manager_vm']['1']['count_foto']='5';
$vehiclemanager_configuration['user_manager_vm']['6']['count_car']='5';
$vehiclemanager_configuration['user_manager_vm']['6']['count_foto']='5';
$vehiclemanager_configuration['user_manager_vm']['7']['count_car']='5';
$vehiclemanager_configuration['user_manager_vm']['7']['count_foto']='5';
$vehiclemanager_configuration['user_manager_vm']['2']['count_car']='5';
$vehiclemanager_configuration['user_manager_vm']['2']['count_foto']='5';
$vehiclemanager_configuration['user_manager_vm']['3']['count_car']='5';
$vehiclemanager_configuration['user_manager_vm']['3']['count_foto']='5';
$vehiclemanager_configuration['user_manager_vm']['4']['count_car']='5';
$vehiclemanager_configuration['user_manager_vm']['4']['count_foto']='5';
$vehiclemanager_configuration['user_manager_vm']['5']['count_car']='5';
$vehiclemanager_configuration['user_manager_vm']['5']['count_foto']='5';
$vehiclemanager_configuration['user_manager_vm']['8']['count_car']='5';
$vehiclemanager_configuration['user_manager_vm']['8']['count_foto']='5';
$vehiclemanager_configuration['user_manager_vm']['10']['count_car']='3';
$vehiclemanager_configuration['user_manager_vm']['10']['count_foto']='3';
$vehiclemanager_configuration['user_manager_vm']['12']['count_car']='0';
$vehiclemanager_configuration['user_manager_vm']['12']['count_foto']='0';
$vehiclemanager_configuration['user_manager_vm']['9']['count_car']='5';
$vehiclemanager_configuration['user_manager_vm']['9']['count_foto']='5';
$vehiclemanager_configuration['user_manager_vm']['11']['count_car']='11';
$vehiclemanager_configuration['user_manager_vm']['11']['count_foto']='0';
$vehiclemanager_configuration['special_price']['show']='1';
// edoc settings
$vehiclemanager_configuration['videos_tracks']['show']='1';
$vehiclemanager_configuration['edocs']['allow']='1';
$vehiclemanager_configuration['edocs']['show']='1';
$vehiclemanager_configuration['edocs']['registrationlevel']='-2';
$vehiclemanager_configuration['edocs']['location']='/components/com_vehiclemanager/edocs/';
$vehiclemanager_configuration['videos']['location']='/components/com_vehiclemanager/media/video/';
$vehiclemanager_configuration['tracks']['location']='/components/com_vehiclemanager/media/track/';
// debuging
$vehiclemanager_configuration['debug']='';
$vehiclemanager_configuration['page']['items']='6';
// foto size
$vehiclemanager_configuration['thumb_param']['show']= '1';
$vehiclemanager_configuration['foto']['high']= '200';
$vehiclemanager_configuration['foto']['width']= '200';
$vehiclemanager_configuration['fotomain']['high']= '420';
$vehiclemanager_configuration['fotomain']['width']= '775';
$vehiclemanager_configuration['fotogallery']['high']= '200';
$vehiclemanager_configuration['fotogallery']['width']= '369';
$vehiclemanager_configuration['fotogal']['high']= '90';
$vehiclemanager_configuration['fotogal']['width']= '90';
$vehiclemanager_configuration['fotoupload']['high']= '600';
$vehiclemanager_configuration['fotoupload']['width']= '1400';
$vehiclemanager_configuration['license']['show']='';
$vehiclemanager_configuration['license']['text']= '<p>Untitled document</p>
<p>License text</p>';
// button '[ Add vehicle ]'
$vehiclemanager_configuration['add_vehicle']['show']='1';
$vehiclemanager_configuration['add_vehicle']['registrationlevel']='-2';
// button '[ print PDF ]'
$vehiclemanager_configuration['print_pdf']['show']='1';
$vehiclemanager_configuration['print_pdf']['registrationlevel']='-2';
// button '[ print View ]'
$vehiclemanager_configuration['print_view']['show']='1';
$vehiclemanager_configuration['print_view']['registrationlevel']='-2';
// button '[ mail_to ]'
$vehiclemanager_configuration['mail_to']['show']='1';
$vehiclemanager_configuration['mail_to']['registrationlevel']='-2';
// send email for admin
$vehiclemanager_configuration['addvehicle_email']['address']='';
$vehiclemanager_configuration['addvehicle_email']['show']='1';
$vehiclemanager_configuration['addvehicle_email']['registrationlevel']='-2';
$vehiclemanager_configuration['review_email']['address']='';
$vehiclemanager_configuration['review_added_email']['show']='1';
$vehiclemanager_configuration['review_added_email']['registrationlevel']='-2';
$vehiclemanager_configuration['rentrequest_email']['address']='';
$vehiclemanager_configuration['rentrequest_email']['show']='1';
$vehiclemanager_configuration['rentrequest_email']['registrationlevel']='-2';
$vehiclemanager_configuration['buyingrequest_email']['address']='';
$vehiclemanager_configuration['buyingrequest_email']['show']='1';
$vehiclemanager_configuration['buyingrequest_email']['registrationlevel']='-2';
// show in category picture
$vehiclemanager_configuration['cat_pic']['show']='1';
$vehiclemanager_configuration['approve_review']['show']='1';
$vehiclemanager_configuration['approve_review']['registrationlevel']='-2';
// show subcategory
$vehiclemanager_configuration['subcategory']['show']='1';
$vehiclemanager_configuration['approve_on_add']['show']='0';
$vehiclemanager_configuration['approve_on_add']['registrationlevel']='-2';
$vehiclemanager_configuration['publish_on_add']['show']='0';
$vehiclemanager_configuration['publish_on_add']['registrationlevel']='-2';
//all_categories
$vehiclemanager_configuration['all_categories']='default';
//view type
$vehiclemanager_configuration['view_type']='default';
//view_vehicle
$vehiclemanager_configuration['view_vehicle']='default';
//show_search_vehicle
$vehiclemanager_configuration['show_search_vehicle']='default';
//all_vehicle_layout
$vehiclemanager_configuration['all_vehicle_layout']='default';
//show location map
$vehiclemanager_configuration['location_map']='1';
//manager_feature_image
$vehiclemanager_configuration['manager_feature_image']='1';
//manager_feature_category
$vehiclemanager_configuration['manager_feature_category']='1';
//sale_separator
$vehiclemanager_configuration['sale_separator']='1';
//extra1
$vehiclemanager_configuration['extra1']='0';
//extra2
$vehiclemanager_configuration['extra2']='0';
//extra3
$vehiclemanager_configuration['extra3']='0';
//extra4
$vehiclemanager_configuration['extra4']='0';
//extra5
$vehiclemanager_configuration['extra5']='0';
//extra6
$vehiclemanager_configuration['extra6']='0';
//extra7
$vehiclemanager_configuration['extra7']='0';
//extra8
$vehiclemanager_configuration['extra8']='0';
//extra9
$vehiclemanager_configuration['extra9']='0';
//extra10
$vehiclemanager_configuration['extra10']='0';
$vehiclemanager_configuration['rss']['show']='1';
$vehiclemanager_configuration['rss']['registrationlevel']='-2';
$vehiclemanager_configuration['owner']['show']='1';
$vehiclemanager_configuration['ownerslist']['show']='';
$vehiclemanager_configuration['ownerslist']['registrationlevel']='';
$vehiclemanager_configuration['calendar']['show']='1';
$vehiclemanager_configuration['calendarlist']['show']='';
$vehiclemanager_configuration['calendarlist']['registrationlevel']='-2';
$vehiclemanager_configuration['rent_answer']='1';
$vehiclemanager_configuration['buy_answer']='1';
$vehiclemanager_configuration['buy_form']='';
//end rent notify
$vehiclemanager_configuration['rent_before_end_notify']='1';
$vehiclemanager_configuration['rent_before_end_notify_days']='2';
$vehiclemanager_configuration['rent_before_end_notify_email']='';
$vehiclemanager_configuration['calendar']['placeholder']='';
$vehiclemanager_configuration['featuredmanager']['placeholder']='Safety,Comfort,Multimedia,Other';
$vehiclemanager_configuration['currency']='USD=1;EUR=8.125;RUB=240;';
$vehiclemanager_configuration['allowed_exts']='zip,pdf';
$vehiclemanager_configuration['allowed_exts_img']='jpeg,jpg,png,gif';
$vehiclemanager_configuration['allowed_exts_video']='mp4,ogv,webm';
$vehiclemanager_configuration['allowed_exts_track']='vtt';
$vehiclemanager_configuration['price_format']=' ';
// 1 - affter 0 - beffore
$vehiclemanager_configuration['price_unit_show']='0';
$vehiclemanager_configuration['date_format']='%Y-%m-%d';
$vehiclemanager_configuration['datetime_format']='%H:%i:%s';
?>